### ISSUE TITLE
Running opensnitchd on boot (Arch Linux)

### ISSUE THREAD

**Issue by OneVoltTen** [evilsocket/opensnitch#102]
Hi, I'm trying to run get opensnitch to run at boot, however running `opensnitchd` as root causes a `dbus` error, any suggestions?

Root log: `[root]# opensnitchd
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
[2017-11-07 09:03:24,705] (INFO) Using rules database from /root/opensnitch.db
Traceback (most recent call last):
  File "/usr/bin/opensnitchd", line 93, in <module>
    snitch = Snitch(dbfile)
  File "/usr/lib/python3.6/site-packages/opensnitch/snitch.py", line 167, in __init__
    self.q.handlers, self.rules)
  File "/usr/lib/python3.6/site-packages/opensnitch/dbus_service.py", line 22, in __init__
    bus = dbus.SessionBus()
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply.`

**Comment by bonebizz21** [comment]
Need help
