### ISSUE TITLE
python2 or python3?

### ISSUE THREAD

**Issue by tetraf** [evilsocket/opensnitch#130]
I bet on python 3 but your requirements file say about futures which is not available with pip 3 and
```
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    service = UIService(app, on_exit)
  File "ui/service.py", line 41, in __init__
    self._setup_interfaces()
  File "ui/service.py", line 55, in _setup_interfaces
    names = array.array('B', '\0' * bytes)
TypeError: cannot use a str to initialize an array with typecode 'B'
```
which seems to be a python-2-code-running-with-python-3-interpreter error.
Then I tried with python 2 but 
```
Traceback (most recent call last):
  File "ui/main.py", line 18, in <module>
    from service import UIService
  File "ui/service.py", line 15, in <module>
    from dialogs.prompt import PromptDialog
  File "ui/dialogs/prompt.py", line 3, in <module>
    import queue
ImportError: No module named queue
```
and if I comment this import I have
```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from service import UIService
  File "ui/service.py", line 15, in <module>
    from dialogs.prompt import PromptDialog
  File "ui/dialogs/prompt.py", line 12, in <module>
    from desktop_parser import LinuxDesktopParser
  File "ui/desktop_parser.py", line 2, in <module>
    import configparser
ImportError: No module named configparser
```
I'm not a python expert (far from it) and I'm a bit lost.

To try with python 2:
```
$ virtualenv2 --system-site-packages ../venv2
$ . ../venv2/bin/activate
(venv2) $ sed -i '/^grpc=/d' requirements.txt
(venv2) $ pip2 install -r requirements.txt
[...]
(venv2) $ python2 main.py --socket unix:///tmp/osui.sock
```
The sed is there to remove
```
Import grpc:No module named gevent.socket
```
cf: https://github.com/grpc/grpc/issues/4100

To try with python 3:
```
$ virtualenv3 --system-site-packages ../venv3
$ . ../venv3/bin/activate
(venv3) $ sed -i '/^futures=/d' requirements.txt
(venv3) $ pip3 install -r requirements.txt
[...]
(venv3) $ python3 main.py --socket unix:///tmp/osui.sock
```

I use the last master commit (99c5456) and  my python versions:
```
(venv2) $ python2 --version
Python 2.7.14
(venv3) $ python3 --version
Python 3.6.4
```

**Comment by evilsocket** [comment]
2
