### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by wcrigger** [evilsocket/opensnitch#131]
Linux Mint 18
Linux wc-desktop 4.4.0-53-generic #74-Ubuntu SMP
go version devel +9745eed Fri Jan 12 05:25:55 2018 +0000 linux/amd64
Python 2.7.12

Not sure this is a bug or not....very likely my inexperience here.  However, in following the README, everything builds/compiles, and daemon starts, but when I get to this:

> And the UI service as your user:
> python /path/to/ui/main.py --socket unix:///tmp/osui.sock

This fails with:

`[09:32 - 1.02]
[wc-desktop 25] ~/go/gocode/src/github.com/evilsocket/opensnitch/ui $ python main.py --socket unix:///tmp/osui.sock
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from service import UIService
  File "/home/warren/go/gocode/src/github.com/evilsocket/opensnitch/ui/service.py", line 15, in <module>
    from dialogs.prompt import PromptDialog
  File "/home/warren/go/gocode/src/github.com/evilsocket/opensnitch/ui/dialogs/prompt.py", line 3, in <module>
    import queue
ImportError: No module named queue`

This indicates to me I'm missing a python module named "queue," right?  A little searching yielded this workaround:

edit ui/dialogs/prompt.py & stats.py from:

`import queue`

to:

`from multiprocessing import Queue`

This brings me to the next error:

`[wc-desktop 57] ~/go/gocode/src/github.com/evilsocket/opensnitch/ui $ python main.py --socket unix:///tmp/osui.sock
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from service import UIService
  File "/home/warren/go/gocode/src/github.com/evilsocket/opensnitch/ui/service.py", line 15, in <module>
    from dialogs.prompt import PromptDialog
  File "/home/warren/go/gocode/src/github.com/evilsocket/opensnitch/ui/dialogs/prompt.py", line 12, in <module>
    from desktop_parser import LinuxDesktopParser
  File "/home/warren/go/gocode/src/github.com/evilsocket/opensnitch/ui/desktop_parser.py", line 2, in <module>
    import configparser
ImportError: No module named configparser`

Have been down a rabbit hole with this one..  I am likely doing something wrong...how to you recommend to proceed?  I've been wanting to check this out but obviously having some problems.  8|

TIA

**Comment by wcrigger** [comment]
...a little reading indicated configparser was part of six, which was already installed...so I did:

`$ sudo -H pip install -U --force-reinstall six
Collecting six
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
Successfully installed six-1.11.0`

...but this did not seem to help.

Thanks again.

**Comment by wcrigger** [comment]
I've also tried:

sudo -H pip install -r requirements.txt --ignore-installed

no bueno.
