### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by tetraf** [evilsocket/opensnitch#149]
```
$ opensnitch-ui
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 36, in <module>
    service = UIService(app, on_exit)
  File "/usr/lib/python3.6/site-packages/opensnitch/service.py", line 45, in __init__
    self._setup_interfaces()
  File "/usr/lib/python3.6/site-packages/opensnitch/service.py", line 70, in _setup_interfaces
    self._interfaces[name] = "%d.%d.%d.%d" % (ord(addr[0]), ord(addr[1]), ord(addr[2]), ord(addr[3]))
TypeError: ord() expected string of length 1, but int found
```
Removing ord() calls at https://github.com/evilsocket/opensnitch/blob/49e30efd5d0cf8ba52cb7dc738706612d73c1607/ui/opensnitch/service.py#L70 seems to fix that.

**Comment by evilsocket** [comment]
fixed
