### ISSUE TITLE
Can't start opensnitch-ui

### ISSUE THREAD

**Issue by cooperq** [evilsocket/opensnitch#177]
```
$ opensnitch-ui 
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 18, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/service.py", line 16, in <module>
    import ui_pb2
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/ui_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'
```
The best I can figure is that protobuf had a change that broke the API but I would appreciate some guidance. Using the latest commit f71d8ce52f79db97f66782c37a2e6506b96e02ad
Python 3.6.5
ubuntu 18.04

**Comment by cooperq** [comment]
Fixed by upgrading protobuf to at least version 3.5
` pip3 install protobuf`
