### ISSUE TITLE
Lot's of tracebacks

### ISSUE THREAD

**Issue by DigiAngel** [evilsocket/opensnitch#2]
Not sure if these are normal or not:
~~~
[2017-04-18 06:01:18,298] (ERROR) Error while parsing DNS response:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opensnitch-0.0.1a1-py2.7.egg/opensnitch/dns.py", line 40, in add_response
    hostname = packet[0][i].rrname
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.3.3-py2.7.egg/scapy/packet.py", line 817, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [13] not found
[2017-04-18 06:01:19,783] (ERROR) Error while parsing DNS response:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opensnitch-0.0.1a1-py2.7.egg/opensnitch/dns.py", line 40, in add_response
    hostname = packet[0][i].rrname
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.3.3-py2.7.egg/scapy/packet.py", line 817, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [13] not found
[2017-04-18 06:01:19,784] (ERROR) Error while parsing DNS response:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opensnitch-0.0.1a1-py2.7.egg/opensnitch/dns.py", line 40, in add_response
    hostname = packet[0][i].rrname
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.3.3-py2.7.egg/scapy/packet.py", line 817, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [13] not found
[2017-04-18 06:01:19,913] (ERROR) Error while parsing DNS response:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opensnitch-0.0.1a1-py2.7.egg/opensnitch/dns.py", line 40, in add_response
    hostname = packet[0][i].rrname
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.3.3-py2.7.egg/scapy/packet.py", line 817, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [6] not found
[2017-04-18 06:01:19,914] (ERROR) Error while parsing DNS response:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opensnitch-0.0.1a1-py2.7.egg/opensnitch/dns.py", line 40, in add_response
    hostname = packet[0][i].rrname
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.3.3-py2.7.egg/scapy/packet.py", line 817, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [6] not found
~~~

Thanks...this is one thing that has always been missing from linux!

**Comment by evilsocket** [comment]
Could u clone and try again?

**Comment by DigiAngel** [comment]
Tracebacks are gone thanks...all I see now are:
~~~
[2017-04-18 06:11:41,002] (WARNING) Could not detect process for connection.
[2017-04-18 06:11:41,002] (WARNING) Could not find process for udp connection 10.0.2.15:60043 -> x.x.x.x:53 inside /proc/net/udp
[2017-04-18 06:11:41,002] (WARNING) Could not detect process for connection.
[2017-04-18 06:11:41,003] (WARNING) Could not find process for udp connection 10.0.2.15:60043 -> 192.168.1.253:53 inside /proc/net/udp
[2017-04-18 06:11:41,003] (WARNING) Could not detect process for connection.
[2017-04-18 06:11:41,004] (ERROR) Error while parsing DNS response: Layer [14] not found
[2017-04-18 06:11:41,006] (ERROR) Error while parsing DNS response: Layer [14] not found
[2017-04-18 06:11:41,007] (ERROR) Error while parsing DNS response: Layer [14] not found
[2017-04-18 06:11:41,020] (ERROR) Error while parsing DNS response: Layer [14] not found
[2017-04-18 06:11:41,023] (ERROR) Error while parsing DNS response: Layer [14] not found
~~~
Also side note, might want to include python-tk in the list of requirements as well :)  Thank you so much for this app.

**Comment by evilsocket** [comment]
These errors might happen if some unpexected DNS response is received, but they're just logged, nothing to really worry about. I'll take a deeper look into it anyway :)

The UI is 100% temporary btw.

**Comment by DigiAngel** [comment]
Ah good deal..looking forward to new builds...can't wait to test :)
