### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [evilsocket/opensnitch#265]
It seems that this error occur when denying a connection having the UI opened. It was reported previously here #225 as a comment of another request.

Steps to try to reproduce it:
- launch the daemon manually or launch _journalctl -f_ 
- open the UI
- launch nmap (nmap 192.168.1.1 -p 1-65000) and allow the connections for the session.
- open a web site: links2 www.duckduckgo.com
- deny each DNS request, using "once", every time (I guess the more times you do this, the more chances you'll have of reproducing it)

[full log daemon_concurrent_map_error.txt](https://github.com/evilsocket/opensnitch/files/3298598/daemon_concurrent_map_error.txt)

```
(...)
jun 17 21:41:15 vv opensnitchd[28438]: github.com/evilsocket/opensnitch/daemon/vendor/google.golang.org/grpc.Invoke(0xa33880, 0xc0016e0f60, 0x9a7414, 0x11, 0x9278a0, 0xc001ce1010, 0x91e840, 0xc001353200, 0xc001362000, 0x0, ...)
jun 17 21:41:15 vv opensnitchd[28438]:         /home/v/go/src/github.com/evilsocket/opensnitch/daemon/vendor/google.golang.org/grpc/call.go:60 +0xc1 fp=0xc001be5e28 sp=0xc001be5da8 pc=0x833fe1
jun 17 21:41:15 vv opensnitchd[28438]: github.com/evilsocket/opensnitch/daemon/ui/protocol.(*uIClient).Ping(0xc001354028, 0xa33880, 0xc0016e0f60, 0xc001ce1010, 0x0, 0x0, 0x0, 0x42e3a1, 0x9c6e20, 0xc001be5f38)
jun 17 21:41:15 vv opensnitchd[28438]:         /home/v/go/src/github.com/evilsocket/opensnitch/daemon/ui/protocol/ui.pb.go:452 +0xd2 fp=0xc001be5eb0 sp=0xc001be5e28 pc=0x856192
jun 17 21:41:15 vv opensnitchd[28438]: github.com/evilsocket/opensnitch/daemon/ui.(*Client).ping(0xc001242780, 0xbf3a1916c82e7018, 0x34f2153aa7, 0xe2e060, 0x0, 0x0)
jun 17 21:41:15 vv opensnitchd[28438]:         /home/v/go/src/github.com/evilsocket/opensnitch/daemon/ui/client.go:128 +0x1e0 fp=0xc001be5f60 sp=0xc001be5eb0 pc=0x861700
jun 17 21:41:15 vv opensnitchd[28438]: github.com/evilsocket/opensnitch/daemon/ui.(*Client).poller(0xc001242780)
jun 17 21:41:15 vv opensnitchd[28438]:         /home/v/go/src/github.com/evilsocket/opensnitch/daemon/ui/client.go:76 +0x18b fp=0xc001be5fd8 sp=0xc001be5f60 pc=0x86113b
jun 17 21:41:15 vv opensnitchd[28438]: runtime.goexit()
jun 17 21:41:15 vv opensnitchd[28438]:         /usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc001be5fe0 sp=0xc001be5fd8 pc=0x45cc21
jun 17 21:41:15 vv opensnitchd[28438]: created by github.com/evilsocket/opensnitch/daemon/ui.NewClient
jun 17 21:41:15 vv opensnitchd[28438]:         /home/v/go/src/github.com/evilsocket/opensnitch/daemon/ui/client.go:48 +0xd6
jun 17 21:41:15 vv opensnitchd[28438]: goroutine 1 [chan receive]:
jun 17 21:41:15 vv opensnitchd[28438]: main.main()     
```

**Comment by gustavo-iniguez-goya** [comment]
This change seems to fix this problem. I can't reproduce it any more, but someone with Go knowledge/experience should verify it :)

```
diff --git a/daemon/ui/client.go b/daemon/ui/client.go
index 3ebc0b4..91039e0 100644
--- a/daemon/ui/client.go
+++ b/daemon/ui/client.go
@@ -119,7 +119,6 @@ func (c *Client) ping(ts time.Time) (err error) {
        }
 
        c.Lock()
-       defer c.Unlock()
 
        ctx, cancel := context.WithTimeout(context.Background(), time.Second)
        defer cancel()
@@ -129,6 +128,9 @@ func (c *Client) ping(ts time.Time) (err error) {
                Id:    reqId,
                Stats: c.stats.Serialize(),
        })
+
+    c.Unlock()
+
        if err != nil {
                return err
        }

```
