### ISSUE TITLE
pip3 install requirements fails in /ui (grpcio)

### ISSUE THREAD

**Issue by greaterthanstar** [evilsocket/opensnitch#275]
Kubuntu 19.04 
Following the instructions exactly I get the following error during `make`. I narrowed it down to this part:
```
cd ui
sudo pip3 install -r requirements.txt
```

```
$:~/go/src/github.com/evilsocket/opensnitch/ui$ sudo -H pip3 --no-cache-dir install -r requirements.txt
Collecting grpcio==1.0.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ba/f7/2138b9148b2d68431ebb05d4871e2fc60deacb4ee282384171083b522823/grpcio-1.0.0.tar.gz (5.3MB)
    100% |████████████████████████████████| 5.3MB 20.3MB/s 
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-fkjz4q_4/futures-3.3.0/setup.py", line 16, in <module>
        # this software without specific prior written permission.
    SystemExit: 1
```

I have Python 2 & 3 installed. Could that be the issue?
```
$python --version
Python 2.7.16
```

**Comment by plutocrat** [comment]
Also getting this on Linux Mint 19.2
`Collecting grpcio==1.0.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ba/f7/2138b9148b2d68431ebb05d4871e2fc60deacb4ee282384171083b522823/grpcio-1.0.0.tar.gz (5.3MB)
    100% |████████████████████████████████| 5.3MB 148kB/s 
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}`

**Comment by plutocrat** [comment]
Seems to work if you comment out the top line in the requirements.txt file which mentions grpcio, and leave all the other lines intact. I guessed this from "Python 3 users do not need it", but I may be wrong.

**Comment by greaterthanstar** [comment]
man thank you do musu fr=or figfuring that ot. I got gott constrant trasin it while it aut0 learns noramlt thinks. so still uneaasy we have a semicorrupt email thougthl gues ill have to look in ti 
1... Thanks!

**Comment by sudoerChris** [comment]
I changed the version to 1.24.0 for both grpcio and grpcio-tools in ui/requirement.txt and successfully installed
grpcio==1.24.0
grpcio-tools==1.24.0

**Comment by Ph0rkoz** [comment]
I just ignored it and never installed. Is this even needed?

**Comment by thomasmodeneis** [comment]
Updating grpcio and tools actually fixed the build after I updated to Ubuntu 19, thanks @sudoerChris

**Comment by DiscreteLoner** [comment]
> I changed the version to 1.24.0 for both grpcio and grpcio-tools in ui/requirement.txt and successfully installed
> grpcio==1.24.0
> grpcio-tools==1.24.0

I did as this suggestion and it works. Mine's version are 1.29.0.
