### ISSUE TITLE
regex compile error when adding a rule : daemon dies

### ISSUE THREAD

**Issue by squalou** [evilsocket/opensnitch#292]
I just faced this issue when adding a block rule :+1: 

```
panic: regexp: Compile(`.*\.vo\.msecnd\.net)`): error parsing regexp: unexpected ): `.*\.vo\.msecnd\.net)`

goroutine 73 [running]:
regexp.MustCompile(0xc001fce980, 0x14, 0xc00006dda0)
	/usr/lib/go/src/regexp/regexp.go:311 +0x154
opensnitch/daemon/vendor/github.com/gustavo-iniguez-goya/opensnitch/daemon/rule.(*Operator).Compile(0xc00006dda0)
	/home/myuser/go/src/opensnitch/daemon/vendor/github.com/gustavo-iniguez-goya/opensnitch/daemon/rule/operator.go:65 +0xf4
```

From a forked repo, sure, will post there too.

PRobably a try / catch around regex would be a quick dirty fix ?
(I don't know how to make sure the entering string is sane, and in this case it was just a regular usage)

**Comment by squalou** [comment]
I've seen the extra parenthesis this time in the dropdown.... :)

**Comment by squalou** [comment]
Closing : issue dealt with on forked repo
