### ISSUE TITLE
UI crashes when doing anything

### ISSUE THREAD

**Issue by shin0x** [evilsocket/opensnitch#472]
Hi there,
first of all thank you for this amazing applications, I really enjoyed using it while it worked.

**Describe the bug**
As soon as I do anything in the guy (e.g pressing deny when an application wants to connect to the internet) the whole GUI crashes.

**To Reproduce**
Pressing anything.

**Post error logs:** 
Error log of the GUI:
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/prompt.py", line 421, in _on_apply_clicked
    self._send_rule()
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/prompt.py", line 448, in _send_rule
    rule_temp_name = self._get_rule_name(self._rule)
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/prompt.py", line 424, in _get_rule_name
    rule_temp_name = slugify("%s %s" % (rule.action, rule.duration))
  File "/home/shinox/.local/lib/python3.9/site-packages/slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined
`
Error log of the service:
`[2021-08-14 11:21:55]  ERR  getting notifications: rpc error: code = Unavailable desc = transport is closing <nil>
[2021-08-14 11:21:55]  WAR  Error while asking for rule: rpc error: code = Unavailable desc = transport is closing - /usr/sbin/chronyd (1751) -> 192.168.188.1:123 (proto:udp uid:989)
[2021-08-14 11:21:55]  ERR  Invalid rule received, applying default action
[2021-08-14 11:21:55]  WAR  Error while pinging UI service: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /tmp/osui.sock: connect: connection refused"
[2021-08-14 11:21:56]  ERR  Connection to the UI service lost.
`

**OS (please complete the following information):**
 - OS: Fedora 
 - Window Manager: GNOME
 - Kernel version: 5.13.9-200.fc34.x86_64
 - Version 34

**Comment by gustavo-iniguez-goya** [comment]
Hi @shin0x ,

mmh, what opensnitch version are you using, 1.3.6? Could you install latest v1.4.0rc3? https://github.com/evilsocket/opensnitch/releases/tag/v1.4.0-rc.3

**Comment by shin0x** [comment]
I was using 1.3.6 after the upgrade to 1.4.0rc3 i still get the same error message

**Comment by gustavo-iniguez-goya** [comment]
ok, according to the logs it seems that you installed python3-slugify via pip. If that's the case, uninstall it and install the one that comes with the distro: `yum install python3-slugify`

Starting from f29 python3-grpcio is available on the repos, so there's no need to install dependencies via pip anymore.
I'd suggest you to uninstall also protobuf and grpcio from pip, and install the ones that come with the distro.

Anyway, as soon as the livecd iso downloads (I'm a ridiculous slow connection, 50KB/s) I'll test the installation.

**Comment by shin0x** [comment]
Thank you very much, as it turned out I installed slugify via pip and package manager, which seemed to result in a few erros.  After removing the pip version and only leaving the package manager version it seems to be working fine now. Thank you very much

**Comment by gustavo-iniguez-goya** [comment]
you're more than welcome :)
