### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TeaWhyDee** [evilsocket/opensnitch#547]
**Describe the bug**
Daemon crashes on start. 

 - OpenSnitch 1.4.0
 - Manjaro x86_64
 - Gnome 40.5
 - Kernel 5.10.70-1-MANJARO
 
**To Reproduce**
I don't know
I was only adding rules based on IP addresses (through the popup).
Also 1 custom one with settings: "To this IP/Network: googlevideo.com"

**journalctl logs (after runing ``systemctl start opensnitchd.service`` ):** 
```
nov 21 23:50:02 tea opensnitchd[12643]: panic: runtime error: invalid memory address or nil pointer dereference
nov 21 23:50:02 tea opensnitchd[12643]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x557531bf0cee]
nov 21 23:50:02 tea opensnitchd[12643]: goroutine 45 [running]:
nov 21 23:50:02 tea opensnitchd[12643]: github.com/evilsocket/opensnitch/daemon/rule.(*Operator).Match(0xc0011640a0, 0xc00084d480)
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/rule/operator.go:209 +0x4ae
nov 21 23:50:02 tea opensnitchd[12643]: github.com/evilsocket/opensnitch/daemon/rule.(*Operator).listMatch(0xc00114e068, {0x557531d65760, 0xc00084d480})
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/rule/operator.go:178 +0x76
nov 21 23:50:02 tea opensnitchd[12643]: github.com/evilsocket/opensnitch/daemon/rule.(*Operator).Match(0xc00114e068, 0xc00084d480)
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/rule/operator.go:211 +0x4e5
nov 21 23:50:02 tea opensnitchd[12643]: github.com/evilsocket/opensnitch/daemon/rule.(*Rule).Match(...)
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/rule/rule.go:65
nov 21 23:50:02 tea opensnitchd[12643]: github.com/evilsocket/opensnitch/daemon/rule.(*Loader).FindFirstMatch(0xc001132000, 0x0)
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/rule/loader.go:402 +0x125
nov 21 23:50:02 tea opensnitchd[12643]: main.acceptOrDeny(0xc0016663f0, 0xc00084d480)
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/main.go:217 +0x68
nov 21 23:50:02 tea opensnitchd[12643]: main.onPacket({{0x557531df9250, 0xc001668a00}, 0x0, 0xc000830420, 0x3e8, 0x4})
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/main.go:203 +0x1a5
nov 21 23:50:02 tea opensnitchd[12643]: main.worker(0x0)
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/main.go:140 +0x94
nov 21 23:50:02 tea opensnitchd[12643]: created by main.setupWorkers
nov 21 23:50:02 tea opensnitchd[12643]:         github.com/evilsocket/opensnitch/daemon/main.go:152 +0xba
nov 21 23:50:02 tea systemd[1]: opensnitchd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
nov 21 23:50:02 tea systemd[1]: opensnitchd.service: Failed with result 'exit-code'.
```

`/var/log/opensnitchd.log` doesn't include any info at the time of crash

I could also send all the rules but I don't know where they are stored. I would also like to reset them so I need the file for that too.

**Comment by gustavo-iniguez-goya** [comment]
Hi @TeaWhyDee ,

Thank you for reporting this error. I'll try to reproduce it. Anyways, don't put domains (googlevideo.com) in the IP/network fields. Use [x] To this host.

**Comment by gustavo-iniguez-goya** [comment]
ok, reproduced. This problem was fixed here: https://github.com/evilsocket/opensnitch/commit/743ef71d7e8b01e0629f54bc2f3296431da56331

I've just merged the fix into the 1.4.0 branch and solves the error. I'll do some more tests.

In the meantime, don't put domains in the IP/Network box. Use `[x] To this host` instead for that.

**Comment by TeaWhyDee** [comment]
@gustavo-iniguez-goya thank you!
I was able to fix the problem by removing the rule file:
``sudo rm /etc/opensnitchd/rules/GOOGLEVIDEO.json``

**Comment by gustavo-iniguez-goya** [comment]
great! I'll publish a new release soon with the fix. Thank you!
