### ISSUE TITLE
runtime exception: option 'x-messagingmenu-useschatsection' in section 'Desktop Entry' already exists

### ISSUE THREAD

**Issue by arielf** [evilsocket/opensnitch#55]
After [Simone's last fix](https://github.com/evilsocket/opensnitch/issues/54) (thanks for fixing so quickly!)

Looks like we're almost there...

```
$ sudo opensnitch
[2017-05-09 10:44:21,812] (INFO) Using rules database from /home/user/opensnitch.db
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch", line 4, in <module>
    __import__('pkg_resources').run_script('opensnitch==0.0.2', 'opensnitch')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/opensnitch-0.0.2-py3.5.egg/EGG-INFO/scripts/opensnitch", line 76, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/opensnitch-0.0.2-py3.5.egg/EGG-INFO/scripts/opensnitch", line 63, in main
    snitch = Snitch()
  File "/usr/local/lib/python3.5/dist-packages/opensnitch-0.0.2-py3.5.egg/opensnitch/snitch.py", line 50, in __init__
    self.desktop_parser = LinuxDesktopParser()
  File "/usr/local/lib/python3.5/dist-packages/opensnitch-0.0.2-py3.5.egg/opensnitch/app.py", line 49, in __init__
    self.populate_app(desktop_file)
  File "/usr/local/lib/python3.5/dist-packages/opensnitch-0.0.2-py3.5.egg/opensnitch/app.py", line 55, in populate_app
    parser.read(desktop_path, 'utf8')
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/usr/share/applications/pidgin.desktop' [line 12]: option 'x-messagingmenu-useschatsection' in section 'Desktop Entry' already exists
```

This seems to be a bug in the original pidgin config file (`/usr/share/applications/pidgin.desktop`) which indeed has a duplicate entry.   It would be nice if we could make configparser only emit a warning/error and not abort in this case (add try/except around it?)

After deleting the duplicate entry, and retrying I get the daemon running.
Thanks for all the fixes!

**Comment by evilsocket** [comment]
Actually it was @adisbladis' fix :)

**Comment by arielf** [comment]
Ah sorry! I stand corrected.  Thank you @adisbladis !
