### ISSUE TITLE
Opensnitch UI crashing when performing actions

### ISSUE THREAD

**Issue by Shadow505** [evilsocket/opensnitch#579]
Hi,

I encountered another bug in the UI... If you're in the Events tab and use it to navigate to the corresponding rule (e.g. by double clicking it) and then perform do anything with that rule, the UI will crash. More detailed:

-) When changing the action (deny/allow):

```
[stats dialog] edit rule, no records:  1 unix:/tmp/osui.sock
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 903, in _cb_table_context_menu
refresh_table = self._configure_rules_contextual_menu(pos)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 744, in _configure_rules_contextual_menu
self._table_menu_change_rule_field(cur_idx, model, selection, "action", Config.ACTION_REJECT)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 783, in _table_menu_change_rule_field
rule = self._rules_dialog.get_rule_from_records(records)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/ruleseditor.py", line 262, in get_rule_from_records
rule = ui_pb2.Rule(name=records.value(2))
AttributeError: 'NoneType' object has no attribute 'value'
fish: Job 1, 'opensnitch-ui' terminated by signal SIGABRT
```

 
-) When attempting to disable the rule:

```
[stats dialog] edit rule, no records:  1 unix:/tmp/osui.sock
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 903, in _cb_table_context_menu
refresh_table = self._configure_rules_contextual_menu(pos)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 724, in _configure_rules_contextual_menu
self._table_menu_enable(cur_idx, model, selection, is_rule_enabled)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 809, in _table_menu_enable
rule = self._rules_dialog.get_rule_from_records(records)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/ruleseditor.py", line 262, in get_rule_from_records
rule = ui_pb2.Rule(name=records.value(2))
AttributeError: 'NoneType' object has no attribute 'value'
fish: Job 1, 'opensnitch-ui' terminated by signal SIGABRT
```

-) When changing the duration:

```
[stats dialog] edit rule, no records:  2 unix:/tmp/osui.sock
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 903, in _cb_table_context_menu
refresh_table = self._configure_rules_contextual_menu(pos)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 730, in _configure_rules_contextual_menu
self._table_menu_change_rule_field(cur_idx, model, selection, "duration", Config.DURATION_1h)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 783, in _table_menu_change_rule_field
rule = self._rules_dialog.get_rule_from_records(records)
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/ruleseditor.py", line 262, in get_rule_from_records
rule = ui_pb2.Rule(name=records.value(2))
AttributeError: 'NoneType' object has no attribute 'value'
fish: Job 1, 'opensnitch-ui' terminated by signal SIGABRT
```

-) When attempting to edit the rule:

It will display a popup, saying: "Rule not found by that name and node". It won't crash the UI (but also not perform what I asked it to do) but will output:

`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3396, resource id: 14680570, major code: 40 (TranslateCoords), minor code: 0`

-) When attempting to delete the rule:

It won't crash (but also not perform what I asked it to do) but will output :

`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3396, resource id: 14680570, major code: 40 (TranslateCoords), minor code: 0`

The cause for these issues is probably pretty similar for all of them, if not identical, due to the fact that they only occur when navigating to them through the events tab.

Version is the latest.

Best regards

**Comment by gustavo-iniguez-goya** [comment]
I've tried to reproduce this problem but it works fine for me with latest sources.

I think you don't have latest sources:
```
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 783, in _table_menu_change_rule_field
rule = self._rules_dialog.get_rule_from_records(records)
```

line 783 of stats.py doesn't have the line `rule = self._rules_dialog.get_rule_from_records(records)`, it have instead:
https://github.com/evilsocket/opensnitch/blob/c70c289bc8143288540060de8ce3956550eaa233/ui/opensnitch/dialogs/stats.py#L783

Verify please that your `/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py` is the same than `https://github.com/evilsocket/opensnitch/blob/master/ui/opensnitch/dialogs/stats.py`

**Comment by gustavo-iniguez-goya** [comment]
Closing. Sources does not correspond with latest from HEAD, so stacktraces are not valid.
