### ISSUE TITLE
opensnitch daemon failed to launch

### ISSUE THREAD

**Issue by molitona** [evilsocket/opensnitch#707]
**Describe the bug**
opensnitch daemon failed to launch after my last upgrade of arch pkgs.

Include the following information:
 - OpenSnitch version: 1.5.0.r19.0aef656-1
 - OS: Arch
 - Window Manager: Gnome
 - Kernel version: 5.18.12-arch1-1

```
╰─ systemctl status opensnitchd.service                                                                                            ─╯
● opensnitchd.service - Application firewall OpenSnitch
     Loaded: loaded (/usr/lib/systemd/system/opensnitchd.service; enabled; preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2022-07-21 21:24:10 CET; 26s ago
       Docs: https://github.com/gustavo-iniguez-goya/opensnitch/wiki
    Process: 7920 ExecStartPre=/bin/mkdir -p /etc/opensnitchd/rules (code=exited, status=0/SUCCESS)
    Process: 7921 ExecStart=/usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules (code=exited, status=2)
   Main PID: 7921 (code=exited, status=2)
        CPU: 670ms

```

```
─ sudo /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules              ─╯
[sudo] password for : 
[2022-07-21 20:22:19]  IMP  Starting opensnitch-daemon v1.5.0
[2022-07-21 20:22:19]  INF  Loading rules from /etc/opensnitchd/rules ...
[2022-07-21 20:22:19]  INF  loading domains lists: lists, lists.domains, /mnt/ads-list
[2022-07-21 20:22:19]  INF  monitor lists started: /mnt/ads-list
[2022-07-21 20:22:19]  INF  clearing domains lists: 0 - /mnt/ads-list
OK: libnetfiler_queue supports nfq_get_uid
OK: libnetfiler_queue supports nfq_get_uid
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55dcbf396b8c]

goroutine 1 [running]:
github.com/iovisor/gobpf/elf.(*Module).UpdateElement.func1(0x14?, 0x1000000000000?, 0x7f11280fc978?, 0x55dcbf1afcc2?, 0x7f1151090108?)
	github.com/iovisor/gobpf@v0.2.0/elf/table.go:75 +0x2c
github.com/iovisor/gobpf/elf.(*Module).UpdateElement(0x55dcbf796d60?, 0xc000dac840?, 0x55dcbf64829d?, 0xa?, 0x55dcbf27e1f4?)
	github.com/iovisor/gobpf@v0.2.0/elf/table.go:79 +0x59
github.com/evilsocket/opensnitch/daemon/procmon/ebpf.Start()
	github.com/evilsocket/opensnitch/daemon/procmon/ebpf/ebpf.go:87 +0x4ed
github.com/evilsocket/opensnitch/daemon/procmon/monitor.Init()
	github.com/evilsocket/opensnitch/daemon/procmon/monitor/init.go:61 +0x65
github.com/evilsocket/opensnitch/daemon/procmon/monitor.ReconfigureMonitorMethod({0xc000dcdd90, 0x4})
	github.com/evilsocket/opensnitch/daemon/procmon/monitor/init.go:29 +0x6c
github.com/evilsocket/opensnitch/daemon/ui.(*Client).loadConfiguration(0xc000ab25a0, {0xc000a94000, 0x165, 0x200})
	github.com/evilsocket/opensnitch/daemon/ui/config.go:100 +0x285
github.com/evilsocket/opensnitch/daemon/ui.(*Client).loadDiskConfiguration(0xc000ab25a0, 0x0)
	github.com/evilsocket/opensnitch/daemon/ui/config.go:52 +0x10a
github.com/evilsocket/opensnitch/daemon/ui.NewClient({0x0, 0x0}, 0xc0000fc8f0, 0xc0000721e0)
	github.com/evilsocket/opensnitch/daemon/ui/client.go:82 +0x105
main.main()
	github.com/evilsocket/opensnitch/daemon/main.go:386 +0x62f
```

**Comment by gustavo-iniguez-goya** [comment]
hey @molitona !

mmh, post please the packages you have installed: https://aur.archlinux.org/packages/opensnitch and https://aur.archlinux.org/packages/opensnitch-ebpf-module ?

that stacktrace may indicate that you're using latest ebpf module from git, instead the one from v1.5.0 branch

**Comment by molitona** [comment]
Hi, @gustavo-iniguez-goya 

I've:
opensnitch-git -> 1.5.0.r19.0aef656-1
opensnitch-ebpf-module-git -> 1.6.0rc2.r0.77f5257-1

Should i install the one from v1.5.0 branch ?. If so, how ?

**Comment by gustavo-iniguez-goya** [comment]
mmh, open the GUI and post the title of the window, for example:

![image](https://user-images.githubusercontent.com/2742953/180429838-639bc6e3-50ea-4cec-b7ea-e632da62d125.png)

Also, execute `$ opensnitchd -version` to verify the daemon version.

**Comment by molitona** [comment]
It's 1.5.0


Jul 22, 2022, 12:27 by ***@***.***:

**Comment by gustavo-iniguez-goya** [comment]
ok, that's the reason of the error. opensnitch-ebpf-module-git -> v1.6.0 is incompatible with daemon v1.5.0

You must update opensnitch-git  , latest version is 1.6.0rc2.r1.96a031a

![image](https://user-images.githubusercontent.com/2742953/180573998-53e1c400-4528-4e9a-a745-e034976f2e6a.png)

I'm not an arch user btw, but I use `$ yay -S opensnitch-git` `$ yay -S opensnitch-ebpf-module-git` to update both packages. There're also others ways of doing it I think.

**Comment by gustavo-iniguez-goya** [comment]
by the way, you may need to delete the modules  `/etc/opensnitchd/opensnitch*.o` before updating opensnitch-ebpf-module-git

**Comment by molitona** [comment]
the last pkg for opensnitch-ebpf-module-git is pkgver=1.6.0rc1.r13.96fbc85
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opensnitch-ebpf-module-git

the last pkg for opensnitch-git is pkgver=1.5.0.r19.0aef656
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opensnitch-git

should i downgarde opensnitch-ebpf-module-git to 1.5.0.r34.e974364-1 ?

**Comment by gustavo-iniguez-goya** [comment]
> should i downgarde opensnitch-ebpf-module-git to 1.5.0.r34.e974364-1 ?

To avoid this error yes.  Or update/reinstall opensnitch-git

**Comment by gustavo-iniguez-goya** [comment]
closing.

**Comment by molitona** [comment]
> > should i downgarde opensnitch-ebpf-module-git to 1.5.0.r34.e974364-1 ?
> 
> To avoid this error yes. Or update/reinstall opensnitch-git

ok, thanks !

**Comment by gustavo-iniguez-goya** [comment]
anyway @molitona , if you can't downgrade, or if the AUR package doesn't compile latest sources from git for whatever reason, you can backup your /etc/opensnitchd/ directory, uninstall AUR packages completely and reinstall them.

**Comment by molitona** [comment]
i uninstall opensnitch-git and opensnitch-ebpf-module-git and reinstall them will fix that opensnitch-git doesn't fetch v1.6 from github repo ?

**Comment by gustavo-iniguez-goya** [comment]
uninstall opensnitch-git and opensnitch-ebpf-module-git , completely. Then reinstall them again.

On manjaro with yay:

Uninstall

```bash
~ $ yay -R opensnitch-ebpf-module-git opensnitch-git                                                                           2 ✘ 
[sudo] password for ga: 
checking dependencies...

Packages (2) opensnitch-ebpf-module-git-1.6.0rc2.r1.96a031a-1  opensnitch-git-1.6.0rc2.r2.f0a9d02-1

Total Removed Size:  15.55 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/2) removing opensnitch-ebpf-module-git                                            [################################################] 100%
(2/2) removing opensnitch-git                                                        [################################################] 100%
warning: /etc/opensnitchd/default-config.json saved as /etc/opensnitchd/default-config.json.pacsave

Optionally remove log file:
sudo rm /var/log/opensnitchd.log

:: Running post-transaction hooks...
(1/4) Reloading system manager configuration...
(2/4) Arming ConditionNeedsUpdate...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
 ~ $ ls /etc/opensnitchd                                                                                                  ✔  18s  
default-config.json.pacnew  default-config.json.pacsave  rules
```
stop or kill opensnitch: `$ sudo systemctl stop opensnitchd; sudo killall opensnitchd opensnitch-ui`

Install

```bash
 ~ $ yay -S opensnitch-ebpf-module-git opensnitch-git                                                                         INT ✘ 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:2]  opensnitch-git-1.5.0.r19.0aef656-1  opensnitch-ebpf-module-git-1.6.0rc1.r13.96fbc85-2

  2 opensnitch-git                           (Build Files Exist)
  1 opensnitch-ebpf-module-git               (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: (1/2) Parsing SRCINFO: opensnitch-git
:: (2/2) Parsing SRCINFO: opensnitch-ebpf-module-git
==> Making package: opensnitch-git 1.5.0.r19.0aef656-1 (Sat Jul 30 16:42:00 2022)
==> Retrieving sources...
  -> Cloning opensnitch git repo...
(...)
==> Validating source files with sha256sums...
    opensnitch ... Skipped
==> Making package: opensnitch-ebpf-module-git 1.6.0rc1.r13.96fbc85-2 (Sat Jul 30 16:42:51 2022)
==> Retrieving sources...
  -> Cloning opensnitch git repo...

(...)
==> Making package: opensnitch-git 1.5.0.r19.0aef656-1 (Sat Jul 30 16:52:00 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating opensnitch git repo...
Fetching origin
==> Validating source files with sha256sums...
    opensnitch ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of opensnitch git repo...
Cloning into 'opensnitch'...
done.
==> Starting prepare()...
==> Starting pkgver()...
==> Updated version: opensnitch-git 1.6.0rc2.r2.f0a9d02-1
==> Sources are ready.
==> Making package: opensnitch-git 1.6.0rc2.r2.f0a9d02-1 (Sat Jul 30 16:52:13 2022)

(...)

```

Notice how the opensnitch-git package version is -> `opensnitch-git 1.5.0.r19.0aef656-1`
But later it's updated to -> `==> Updated version: opensnitch-git 1.6.0rc2.r2.f0a9d02-1`

The last part, `f0a9d02` is the latest commit (as of today) to the master branch f0a9d02.

**Comment by molitona** [comment]
Thank you, it's resolved!
