### ISSUE TITLE
v1.6.0-rc.5 does not run on Ubuntu 23.04 (Gnome)

### ISSUE THREAD

**Issue by LANopop** [evilsocket/opensnitch#961]
opensnitch v1.6.0-rc.5
Ubuntu 23.04
6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

errors when running opensnitch-ui
```
Themes not available. Install qt-material if you want to change GUI's appearance: pip3 install qt-material.
	 ~ OpenSnitch GUI - 1.6.0rc5 ~
	protobuf: 4.21.12 - grpc: 1.51.1
-------------------------------------------------- 

Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
QSocketNotifier: Can only be used with threads started with QThread
Using server address: unix:///tmp/osui.sock
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 2
setting schema version to: 2
schema version: 2
db schema is up to date
using IPASN DB: /usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz
E0607 13:56:37.944187288 2169058 chttp2_server.cc:1045]                UNKNOWN:No address added out of total 1 resolved for 'unix:/tmp/osui.sock' {created_time:"2023-06-07T13:56:37.94401085+02:00", children:[UNKNOWN:Unable to configure socket {created_time:"2023-06-07T13:56:37.943995737+02:00", fd:51, children:[UNKNOWN:Address already in use {created_time:"2023-06-07T13:56:37.943992845+02:00", errno:98, os_error:"Address already in use", syscall:"bind"}]}]}
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 149, in <module>
    server.add_insecure_port("unix:%s" % socket)
  File "/usr/lib/python3/dist-packages/grpc/_server.py", line 970, in add_insecure_port
    return _common.validate_port_binding_result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/grpc/_common.py", line 175, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address unix:/tmp/osui.sock; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
```

errors when running sudo opensnitch-ui

```
Themes not available. Install qt-material if you want to change GUI's appearance: pip3 install qt-material.
	 ~ OpenSnitch GUI - 1.6.0rc5 ~
	protobuf: 4.21.12 - grpc: 1.51.1
-------------------------------------------------- 

Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Using server address: unix:///tmp/osui.sock
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 2
setting schema version to: 2
schema version: 2
db schema is up to date
DesktopNotifications not available (install python3-notify2): org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
using IPASN DB: /usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz
DesktopNotifications not available (install python3-notify2): org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
```

errors when running sudo QT_QPA_PLATFORM=xcb opensnitch-ui

```
Themes not available. Install qt-material if you want to change GUI's appearance: pip3 install qt-material.
	 ~ OpenSnitch GUI - 1.6.0rc5 ~
	protobuf: 4.21.12 - grpc: 1.51.1
-------------------------------------------------- 

Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Using server address: unix:///tmp/osui.sock
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 2
setting schema version to: 2
schema version: 2
db schema is up to date
DesktopNotifications not available (install python3-notify2): org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
using IPASN DB: /usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz
DesktopNotifications not available (install python3-notify2): org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
```

**Comment by gustavo-iniguez-goya** [comment]
hi @LANopop ,

How did you first realize that there was a problem? what was the first indicator of an error?

On the other hand, the first error says: `os_error:"Address already in use"` , so it looks like there was already a GUI running.

Before launching the GUI from a shell, check out that the process `opensnitch-ui` is not already running.

> errors when running sudo opensnitch-ui

don't launch the GUI as root. Launching it as your regular user is enough, and preferable.

**Comment by LANopop** [comment]
no icon on the systray
i use gnome and wayland

**Comment by gustavo-iniguez-goya** [comment]
aah, ok, then you have to install this extension: https://extensions.gnome.org/extension/615/appindicator-support/

I think it's available on the ubuntu's repositories:  gnome-shell-extension-appindicator
